### ISSUE TITLE
Remove Range

### ISSUE THREAD

**Issue by DanyCryEn** [saltminede/saltychat-docs#32] opened 2021-05-09 22:24 UTC
i don't know how set Radio Towers... and people can't help me... i've read the README but i don't understand what i've to do... 

Have possibility to disable Range, and make open radio in all world? ... thanks

**Comment by xnubil** [comment] 2021-05-09 22:55
Set radio type to Long Range (4), 8km is larger than the map itself

**Comment by DanyCryEn** [comment] 2021-05-10 10:42
i've set on long range, but is not all map range.

**Comment by izzmatteo** [comment] 2021-05-10 18:56
Have the same problem! I don't understand anyone who  is in Paleto Bay, for example!

**Comment by Hanashi** [comment] 2021-05-10 19:00
> Set radio type to Long Range (4), 8km is larger than the map itself

That's not right. The map is bigger than 8km.

You must use distributed radios via radio towers. Define the radio towers and set your `RadioType` + `Distributed` (look at [RadioType Enum](https://github.com/saltminede/saltychat-docs/blob/master/enums.md#radio-type)).

For e.g. LongRange (4) + Distributed (8) = 12

**Comment by xnubil** [comment] 2021-05-10 20:05
> > Set radio type to Long Range (4), 8km is larger than the map itself
> 
> That's not right. The map is bigger than 8km.
> 
> You must use distributed radios via radio towers. Define the radio towers and set your `RadioType` + `Distributed` (look at [RadioType Enum](https://github.com/saltminede/saltychat-docs/blob/master/enums.md#radio-type)).
> 
> For e.g. LongRange (4) + Distributed (8) = 12

My mistake on the map size. I have RadioType 24 Distrubuted + USR, with 7 towers placed in key areas and have full map coverage, with a few low signal spots. Works quite well

**Comment by Hanashi** [comment] 2021-05-11 13:00
This issue is a duplicate to #19

**Comment by izzmatteo** [comment] 2021-05-11 16:50
> > > Set radio type to Long Range (4), 8km is larger than the map itself
> > 
> > 
> > That's not right. The map is bigger than 8km.
> > You must use distributed radios via radio towers. Define the radio towers and set your  +  (look at [RadioType Enum](https://github.com/saltminede/saltychat-docs/blob/master/enums.md#radio-type)).`RadioType``Distributed`
> > For e.g. LongRange (4) + Distributed (8) = 12
> 
> My mistake on the map size. I have RadioType 24 Distrubuted + USR, with 7 towers placed in key areas and have full map coverage, with a few low signal spots. Works quite well

How do you that? Where i have to set it?

**Comment by xnubil** [comment] 2021-05-11 17:37
https://github.com/saltminede/saltychat-fivem/blob/6f086c74dfa65dbfdfabd82de253f65666d4a803/saltychat/config.json#L13

Set the RadioType to 24 ( 8 for Distributed, 16 for Ultra Short Range )

**Comment by izzmatteo** [comment] 2021-05-12 05:32
And where i can Set Radio Towers?

xnubil ***@***.***> schrieb am Di., 11. Mai 2021, 19:38:

**Comment by xnubil** [comment] 2021-05-12 10:15
Join the discord, lots of examples

**Comment by izzmatteo** [comment] 2021-05-12 10:18
> Join the discord, lots of examples

I am on the discord! Can you send me a screen of you Config? When i tryed it it dont work! Nobody heard anyone!

**Comment by xnubil** [comment] 2021-05-12 10:20
I just copied it from the discord. Make a table with coords and send them all at once to saltychat

**Comment by izzmatteo** [comment] 2021-05-12 10:42
> ‎Ich habe es einfach aus der Zwietracht kopiert. Machen Sie einen Tisch mit Coords und senden Sie sie alle auf einmal zu saltychat‎

I actually did it that way! But I made the Radio Towers into an external script! Is that right? 
DiscordName: izz Matteo#4456

**Comment by xnubil** [comment] 2021-05-12 11:52
Yes, my towers are in a seperate script

**Comment by izzmatteo** [comment] 2021-05-12 15:17
> Yes, my towers are in a seperate script

It dosen`t work for me

**Comment by BlackFlash5** [comment] 2021-05-13 15:50
Duplicate of #31 and maybe #19

**Closed by BlackFlash5** 2021-05-13 15:50 UTC

**Comment by timonation** [comment] 2021-09-29 17:54
> Have the same problem! I don't understand anyone who is in Paleto Bay, for example!

any solution? i have the same issue. radiotype 8 fix the problems ? please help
