### ISSUE TITLE
[Feature-Request] Add IsHardwareInputEnabled and IsHardwareOutputEnabled state in the Command 6 - SoundState

### ISSUE THREAD

**Issue by MypowerHD** [saltminede/saltychat-docs#15] opened 2020-05-31 13:21 UTC
It would be nice if we can check that the Player has no Input or Output Hardware enabled.
In the plugin sdk it handled over the HardwareInputStatus and HardwareOutputStatus.

https://github.com/TeamSpeak-Systems/ts3client-pluginsdk/blob/a39d50383b4a023941c31c08fe0c9766b149ed01/include/teamspeak/public_definitions.h#L80

**Comment by BlackFlash5** [comment] 2020-06-14 20:30
Got this implemented in 2.0.0, but unfortunately TeamSpeak doesn't trigger the client variable update when you join another TeamSpeak server, where the mic gets disabled automatically.

**Comment by riffy** [comment] 2020-06-30 17:31
So there is currently no way to capture this behavior ?
![mic_deactivated](https://user-images.githubusercontent.com/13089522/86157684-0f5b5e00-bb08-11ea-8f5c-de0b79229097.PNG)

Maybe the Input Disable/Enable can still be treated then as IsMicrophoneMuted and IsSoundMuted

**Comment by BlackFlash5** [comment] 2020-06-30 18:02
I got a solution for this, which will be in 2.0.0p2.
The issue is, that TeamSpeak updates the client property `CLIENT_INPUT_HARDWARE` only on the connection tab where the mic will be enabled and completely forgets about the tab where the mic was active.
So if you have to listen for that and set the mic as disabled, when it gets enabled on any other tab.

**Comment by BlackFlash5** [comment] 2020-07-15 20:41
2.0.0 is with this feature implemented on the stable branch.

**Closed by BlackFlash5** 2020-07-15 20:41 UTC
Labels: confirmed, enhancement
